z411/trackma

- trackma/ui/qtui.py
- trackma/utils.py
Something I proposed in the past. Upon closing the application, the geometry is stored. I'm not sure whether I'm using the config file the right way, so feel free to correct (or reject) it if you don't like it.
> Remember geometry of Qt GUI when closing the application

- trackma/ui/qtui.py
This simply clears the current selection before a search occurs. If only a single result was present, it became impossible to select it as it seemed to be selected already. Sorry for the merge commits, forgot to rebase. ^^;
Edit: It works if you simply click another column. Kinda confusing, though.
> Fix a bug where a single result wouldn't be selected in search

- trackma/lib/libanilist.py
This fixes two bugs at libanilist.
Parsing bug: in the parsing function, instead of using the string that change with the mediatype (self.airing_str), 'airing_status' is used. This prevents the manga statuses to be parsed.
Retrieve bug: anilist added some months ago the cancelled status, if you have in your list one item that has this status, trackma raises a KeyError. I set cancelled to 4, but 2 could do, cancelled is like finished.
> Anilist status fixes

- trackma/ui/qtui.py
In the Qt interface, the play next button existed, but it was never added to a layout. This adds it underneath the play button.
> Made the Qt play next button visible

- trackma/ui/cli.py
The cli's sort command doesn't work because of a typo, this commit fixes it.
> CLI: Fixed typo that breaks sort command

- AUTHORS
- trackma/ui/qtui.py
- trackma/utils.py
Allows user customisation of row highlight colors. Supports arbitrary colors as well as colors from the Qt theme (options dialog only shows background roles since foreground roles are very likely to have little contrast to the text, but any valid roles can be entered in the config json).
> [Qt] Customisable row highlights

- trackma/ui/qtui.py
- trackma/utils.py
Should make running multiple instances for different APIs a bit more manageable.
> [Qt][Option] Use the current API icon as the tray icon

- trackma/lib/libanilist.py
The anilist API returns an empty response when you delete an entry. At the _request function, the response is parsed and raise a ValueError. The entry is deleted at anilist, but trackma crashes.
I used a try/except just like in the search function. First, I did `if method == "DELETE"` in _request, but I think it's better this way because it only runs when the delete function is called.
> libanilist: Fixed an exception when trying to delete

- trackma/ui/gtkui.py
- trackma/utils.py
Adds color selection for show text and the components of the progress/percent widget to the settings dialog. No theme-aware colors so not a true fix for #153 but it should be of some use to Gtk users.
> [Gtk] Configurable show and progress widget colors

- trackma/lib/libanilist.py
- trackma/ui/qtui.py
- trackma/utils.py
Reordered the info and renamed some data to be more in line with libmal, fixed URL generation. Uses airing data from the anilist browse API (1 request per sync, ~150kB json) to determine number of episodes aired for airing shows. Replaces defunct (start-)date column for anilist anime with a simple days,hours countdown to the next episode (only updates on table regeneration, I may revisit this later).
Anilist API version bump from 1 to 1.1
> [Anilist][Utils][Qt] Anilist improvements

- trackma/ui/gtkui.py
- trackma/utils.py
Added options for remembering window geometry (#140), using standard progress bar widgets (#153) and using API icons in the tray (port of #159). Fixed percent sort.
I'm giving up on overlaying the episode subbar onto the standard widget in Gtk, but I'll probably get around to adding a theme-aware colour picker within the next week.
> [Gtk] Minor additional options

- trackma/ui/qtui.py
- trackma/utils.py
Replaces episode selection dialog with a series of submenus. Longer series will have more levels of submenus. I've used breakpoints that I feel strike a good balance of menu size and levels of submenus, but if you wish to tweak them the variables are labelled and at the top of the generate_episode_menus method. Unreasonably long shows will fall back to the numeric dialog, but with the supplied breakpoints you'd be hard pressed to find a show with that many episodes :3c
Also changed the aired eps estimation function to disregard totals of 0.
Related Issues: #132, #164
> [Qt] Play episode submenu selection

- trackma/ui/gtkui.py
- trackma/ui/qtui.py
- trackma/utils.py
Adds an option to have separate visible columns settings per API. These are stored in ui-qt.{api}.json, which might be used for additional future features that may warrant having different settings between APIs.
> [Qt] Columns per api

- trackma/accounts.py
- trackma/utils.py
Since accounts.dict stores usernames and passwords, most (Unix) applications typically create such files to be read/writable only by owner. This patch does just that by allowing accounts.AccountManager.save to change the file permissions on initialization. Since this is only done once, the user can manually change the permissions on accounts.dict to allow group or all access, and future saves will respect those permissions.
It's a minor security change, but I just feel fidgety when I see my passwords in a globally readable file. :)
> Modify accounts.dict to initialize with mode 0600

- trackma/ui/qtui.py
- Filter refresh on any list changes. Prevents strange behaviour when shows are added.
- AddDialog selects the first item after every search and fetches data.
> [Qt] Remove some stale data incidents

- trackma/ui/qtui.py
- trackma/utils.py
- Added option to place filter bar above the lists, or hide it entirely.
- When the filter is active, the title of the list will show the number of matching shows out of the total.
- To use this to get number of matches across all lists, an option has been added to make the filter update all lists (disabled by default for speed concerns).
> [Qt] Filter bar additions

- trackma/accounts.py
- trackma/ui/qtui.py
- trackma/utils.py
Imports most PyQt classes directly into the namespace, sidestepping the issue of PyQt5 reorganising the modules. Checks are added for the few methods which have had their names changed.
Account dialog edit functionality was accidentally included in the merge process but I would have submitted that at some point in the future anyway so I didn't bother removing it.
This branch contains #198 and #199, if those are not desired [Qt5Base branch](https://github.com/Birdulon/trackma/tree/Qt5Base) contains the Qt5 changes without those fixes.
> [Qt] PyQt5 Support (part of #120)

- trackma/engine.py
Catches the error gracefully instead of crashing out completely.
Somewhat fixes #202.
> Error escape play_random when no episodes are added to randomly pick from

- trackma/ui/qtui.py
An oversight of mine when I changed the PyQt4 API version.
> [Qt] Fixed AttributeError when switching mediatypes in Qt4.

- trackma/ui/gtkui.py
- trackma/ui/qtui.py
Fixes #189.
Should the cache or filenames matching the old pattern be cleared on startup? Worst-case people will have some MB of useless images in their cache until they manually clean it up, so I don't see the need to.
> [Qt][GTK] Prefix cache images with (apishortname)_(mediatype)_

- trackma/ui/qtui.py
During my work on #212, I discovered that Qt UI has broken simple progress bar style:
```console
rr-@tornado:~/src/ext/trackma$ trackma-qt
Warning: DateUtil is unavailable. Next episode countdown will be disabled.
Data: Locking database...
Data: Reading metadata...
Data: Reading queue...
Data: No items in queue.
libmal: Logging in...
Data: Saving userconfig...
libmal: Downloading list...
libmal: Parsing anime list...
Data: Saving cache...
Data: Saving metadata...
Tracker: Initializing...
Tracker: Enabling tracker...
Tracker: inotifyx not available; using polling (slow).
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/qtui.py", line 2555, in paintEvent
prog_options = QtGui.QStyleOptionProgressBarV2()
AttributeError: 'module' object …
```
> [Qt] fix simple progress bar style

- trackma/tracker.py
- trackma/ui/qtui.py
Adds support for pyinotify and (PyPi) inotify, similarly to how inotifyx was handled (i.e. poll with lsof whenever there's an IN_OPEN or IN_CLOSE_(NO)WRITE, and update every second when a video is opened).
Also watches any folders created in the watch directory after the tracker starts, which is something new over the old inotifyx support.
Addresses #218.
> [Tracker] Inotify support (#218)

- trackma/ui/qtui.py
- Fixes the show/hide columns context menu not changing when switching accounts
- Makes columns show (unhide) with a minimum width to prevent confusion arising from zero-width columns
> [Qt] Column cleanup

- trackma/ui/qtui.py
Some UI adjustments:
-  it's better not to set minimum window size in this case, due to possibility of rendering  issues (overlapping widgets) with different font sizes etc.
-  less cluttered button layout
> [Qt] UI adjustments

- trackma/lib/libanilist.py
Changes the status translation of completed manga in the Anilist library to reflect changes (?) to the API.
Fixes trackma crashing due to KeyError when using Anilist.
> Fix KeyError due to completed manga status

- setup.py
refer to  `pygobject` in the GTK requirements, so that setuptools can find it.
Fixes #228; tested on Arch Linux, but will probably work the same on other distributions.
> setup.py: fix requirements issue with `gi` package.

- trackma/lib/libanilist.py
Anilist API now sends a small JSON error object in case the search has found no results. 
It's possible some other functions need updating too, but I haven't found anything so far.
> libanilist: fix search function

- trackma/data.py
- trackma/ui/cli.py
Implements #241. 
I also extended the title length and dot padding to the maximum length instead of `col_title_length` because when encountering titles that used up the full length (something that might become more common when also showing the alternative names) their rows would be misaligned like so:
This might just be on my side though, but either way, I think giving the titles the most room looks better anyway, and `col_title_length` is taken into account by the maximum length anyway.
Lastly, fixed a small KeyError on trying to clear an alternative title where there was none.
> CLI Altnames

- CHANGELOG
Simple mistake in changelog. Open containing folder was added to gtk not qt.
> changelog fix: open containing folder was added to gtk

- trackma/engine.py
- trackma/tracker.py
- trackma/ui/qtui.py
- trackma/utils.py
Adds an option to prompt to add new shows to your list as/after you watch them. The prompt is the same as the regular search/add from remote dialog, however it starts with the show title filled in (not searched without user input to prevent privacy leaks) and closes after a show is successfully added, then updates the episode counter to match the one that was detected.
Known issue: Changing tracker options requires a restart to take effect. Would it be overkill to add a tracker restart to settings changes that involve the tracker?
> [Tracker][Engine][Qt] Prompt to add unrecognised shows.

- trackma/tracker.py
Adds another safety check similar to 1d0e527 but for wait_close=False, which prevents the tracker from crashing when there is a previous show tuple but the previous state is not STATE_PLAYING. Should fix #255.
> [tracker] Remove another assumption

- trackma/ui/qtui.py
Workaround taken from the bottom of https://www.tbi.univie.ac.at/~pmg/tutorials/QT/html/geometry.html
I'm disgusted by the need for it, but it seems to fix the problem on my window manager setup.
EDIT: If someone on Windows could test this it would be much appreciated!
> [Qt] Split setGeometry into resize and move. (fixes #246)

- trackma/ui/qtui.py
Small oversight, shows don't have the dict entry until resyncing.
> [Qt] Fixed not being able to edit tags on just added items

- trackma/lib/libkitsu.py
I've just put the romaji title in the first position.
Why? Because now trackma shows `Attack on Titan`, and I prefer to have the more knowing name `Shingeki no Kyojin`.
Thank you
> Put the romaji title in the first position

- trackma/engine.py
- trackma/ui/gtkui.py
- trackma/ui/qtui.py
- trackma/utils.py
Implements #181.
To recap this PR adds the following:
+ The engine now optionally scans the mediafolder for series from all non-completed statuses (PTW/On-    Hold/Dropped)
+ Added a setting that en- or disables this feature (disabled by default)
+ Added corresponding settings to the GUIs (including a missing 'scan lib at startup for GTK)
+ The GUI remains operable whilst scanning
The pros and cons of this feature have been discussed, but it's probably fine as it is? I made it an optional feature to begin with, it's there for those that want it, and if it's too much of a drain it can be turned off.
Since I've had little feedback I figured I'd file a PR anyway and let you decide whether to merge it now or if it still needs work
Possible things to improve:
> Scan library for multiple statuses

- trackma/engine.py
Not sure how this made it into master but it totally borks the whole thing for me since latest pull.  This *may* be because I'm on python 3.6.2, don't have time to test on other versions though.  Anyhow, this fixes it for me, or so it seems.
> Fix typo, fix isinstance() call

- trackma/ui/gtkui.py
- trackma/ui/qtui.py
e81db16 fixes the sort IDs in GTK. They should start from 1 because the ID of Title column is 1.
94b15c8 enables sorting in Qt.
The sorting is still kind of wonky for the Total field because the values are number strings.
> Small fixes to GTK and Qt search view sorting

- trackma/ui/qtui.py
Fixes a bug where the list rows wouldn't be updated even with the 'Scan through whole list' option enabled, even though the files were detected.
> Qt - Update row colors when scanning whole list (fixes #314)

- trackma/data.py
- trackma/tracker/plex.py
This is just because i was getting a bunch of crashes from the plex tracker.
Some exceptions due to each `observe()` not being atomic (i.e. the status can go `NOT_RUNNING` after it was last checked but before the xml info is needed).
Also a queue atomicity issue.
> Fix plex tracker crashes

- trackma/lib/libanilist.py
Some shows on Anilist lack one or more titles.
Currently the `fetch_list` method accounts for this, only adding the names that exist as aliases, but the `search` method does not (my bad!), which passes `None`s to the aliases, causing a tracker crash if certain shows are added after a search with no list re-download.
I also noticed some other strangeness when adding new shows straight from a search (nonsensical error messages like "show not found" and the show still being added) but have not been able to reproduce them reliably, hopefully that was just another symptom of my oversight on this.
> [libanilist] Fix search possibly adding null names as show aliases

- trackma/ui/gtkui.py
- trackma/ui/qtui.py
Fixes crashing for QT and an error from GTK when you don't have PIL installed and try to load a thumbnail.
> [QT, GTK] fixes for when PIL is unavailable

- trackma/lib/libkitsu.py
Hello friends,
The current kitsu behaviour is to fetch only the series "start" and "finish" dates, but not the user timetables. This small addition adds the latter. Please double check as this is my first commit. >_<
> libkitsu: add missing user start & finish dates

- trackma/engine.py
- trackma/tracker/inotify.py
- trackma/tracker/pyinotify.py
- trackma/tracker/tracker.py
Fixes #382.
Call tracker.disable() when unloading engines.
Check tracker active state before reacting to incoming events.
Remove unused tracker.enable() method.
> Clean up trackers when unloading engines

- trackma/engine.py
Sorry, guess I didn't test changing from an account/media type without a tracker.
> Don't attempt to disable engine.tracker when there is no tracker

- trackma/tracker/plex.py
PYTHON_E225: 'Fix extraneous whitespace around keywords.'.  This is a pep8 error code.          See <a href='https://pep8.readthedocs.io/en/latest/intro.html#error-codes'>        here for a complete list of error codes</a>.
It was fixed with <a href='https://github.com/hhatto/autopep8'>autopep8</a>.  The fix is completely safe.
> Fixed 1 issue of type: PYTHON_E225 throughout 1 file in repo.

- trackma/tracker/plex.py
Fixes #393, only for claimed servers because it's the only way to get user info (to identify who is watching it), only tracks if the login username and the user watching the video returned by plex match.
Also, display a different message when the server is claimed and trackma can't access it (because login info is needed).
> Fixes #393 (only for claimed severs), and display a message when the sever is claimed. 

- trackma/tracker/inotifyBase.py
- trackma/tracker/tracker.py
The tracker will now consider subdirectory names if the `library_full_paths` config setting is enabled. This fixes the bug with shows not being tracked if the names are only in the directories and not the files.
> trackma.tracker: Implement support for tracking via full paths

- trackma/ui/gtk/mainview.py
The treeview was not getting the number of decimals and instead we were
only passing it to the notebookpage class. Also we were updating the
decimals after populating the treeview, so we never got them.
Fix #407
> Gtk: Fix decimals in show treeview

- trackma/ui/cli.py
```
>> add "asd
Traceback (most recent call last):
File "/home/fichte/code/trackma/trackma/ui/cli.py", line 718, in parse_args
return shlex.split(arg)
File "/usr/lib/python3.7/shlex.py", line 305, in split
return list(lex)
File "/usr/lib/python3.7/shlex.py", line 295, in __next__
token = self.get_token()
File "/usr/lib/python3.7/shlex.py", line 105, in get_token
raw = self.read_token()
File "/usr/lib/python3.7/shlex.py", line 187, in read_token
raise ValueError("No closing quotation")
ValueError: No closing quotation
```
> CLI: Don't crash on shlex errors i.e. unclosed quotes

- trackma/lib/libkitsu.py
Current kitsu api provides rating and ratingTwenty for rating.
As rating is now deprecated we should use ratingTwenty.
> Use attributes.ratingTwenty in libkitsu

- trackma/utils.py
Fixes strings being erroneously passed to the rest of the program when LINES and COLUMNS are specified, as one might do for #454. Additionally, allows specifying COLUMNS without LINES (and vice-versa though that is not as useful).
The end result is that `COLUMNS=130 trackma list > list.txt` will produce expected output.
> [CLI] Environment variable fix for #454

- trackma/ui/qt/add.py
- trackma/ui/qt/mainwindow.py
Card View is preferable because all items have a graphical poster which makes them more visually distinguishable
> Qt: make Card View the first option for the Search Dialog

- trackma/ui/qt/widgets.py
The default order returned by an API would be more useful and would
keep the searched show somewhere on the top.
> Qt: Don't sort the table-view by default when searching shows

- trackma/ui/qt/settings.py
Settings page would overflow and take the buttons out of the screen/dock
on screens with smaller resolutions (eg. 1366x768).
This will add a scroll bar if the pages would overflow.
> Qt: Make settings pages scrollable

- trackma/ui/qt/mainwindow.py
Changed in Qt 5.14: https://doc.qt.io/qt-5/qactiongroup.html#ExclusionPolicy-enum
> Qt: use `exclusionPolicy` instead of `exclusive`

- trackma/ui/qt/add.py
- trackma/ui/qt/mainwindow.py
* Using `doubleClicked` signal as the `activated` signal is triggered inconsistently on different
platforms/settings.
Reference: https://doc.qt.io/qt-5/qabstractitemview.html#activated
*  Show a message box as feedback when a show is added
Fixes #461
> [Qt] Use doubleClicked signal and add success message box in add dialog

- README.md
Void Linux has change their github repository few years ago (see : https://wiki.voidlinux.org/Xbps-src)
> Update Void Linux repository URL in README

- trackma/data.py
- trackma/tracker/mpris.py
- trackma/ui/gtk/accountswindow.py
- trackma/ui/gtk/application.py
- trackma/ui/gtk/data/settingswindow.ui
- trackma/ui/gtk/gi_composites.py
- trackma/ui/gtk/imagebox.py
- trackma/ui/gtk/mainview.py
- trackma/ui/gtk/searchwindow.py
- trackma/ui/gtk/settingswindow.py
- trackma/ui/gtk/showinfobox.py
- trackma/ui/gtk/showinfowindow.py
- trackma/ui/gtk/showtreeview.py
- trackma/ui/gtk/statusicon.py
- trackma/ui/gtk/window.py
- Stop spinner on search failure.
- Update Headerbar subtitle and Results view to reflect search failure.
- Reenable UI after finishing 'Scan files' action.
> Fix some major and minor issues in Gtk UI.

- trackma/ui/cli.py
- trackma/utils.py
When requesting the info of a tracked item, the CLI returns the internal value instead of a human-readable string.
Before
After
> CLI: Show status in info instead of numeric value

- trackma/ui/qt/accounts.py
- trackma/ui/qt/add.py
- trackma/ui/qt/mainwindow.py
- trackma/ui/qt/settings.py
- trackma/ui/qt/widgets.py
Became a SyntaxWarning in Python 3.8 and has been wrong since forever.
> Remove 'is' comparisons with literals

- trackma/ui/qt/mainwindow.py
Fixes everything that https://github.com/z411/trackma/pull/468/commits/71f198a8da251d6b8eb94281317fa2c183743043 broke.
> Qt: use `setExclusive` for backward compatibility

- trackma/ui/gtk/main.py
If we ignore SIGCLD then init(1) automatically reaps child process on exit and this fixes not getting player process close event on polling/inotify trackers.
Fixes #508
> Ignore SIGCLD to prevent keeping zombie process.

- trackma/ui/gtk/accountswindow.py
- trackma/ui/gtk/application.py
- trackma/ui/gtk/data/accountrow.ui
- trackma/ui/gtk/data/accountswindow.ui
- trackma/ui/gtk/data/mainview.ui
- trackma/ui/gtk/data/settingswindow.ui
- trackma/ui/gtk/gi_composites.py
- trackma/ui/gtk/imagebox.py
- trackma/ui/gtk/main.py
- trackma/ui/gtk/mainview.py
- trackma/ui/gtk/searchwindow.py
- trackma/ui/gtk/settingswindow.py
- trackma/ui/gtk/showinfobox.py
- trackma/ui/gtk/showinfowindow.py
- trackma/ui/gtk/showtreeview.py
- trackma/ui/gtk/statusicon.py
- trackma/ui/gtk/window.py
Made several changes that are not immediately visible. The commit messages are hopefully descriptive enough.
- Now uses a GtkPopover for setting episode number.
- Use a GtkButtonBox for the episode number, "+" and "-" buttons.
- Stop using "Gtk.STOCK_" items because they've been deprecated and use suggested alternatives from GTK docs.
- Library info (i.e. "Anilist [manga]") is now in the subtitle instead of the title and is now updated properly.
- Some spacings have been fixed to match the GNOME HIG and results in a more pleasant UI.
There are a few changes that are personal opinions and can be reverted if necessary:
- "Trackma-gtk" is less suited for use anywhere other than the CLI. So, I've renamed all instances of it within the UI to "Trackma GTK" and just "Trackma" in the application …
> Fix some issues with the GTK GUI

- trackma/engine.py
- trackma/tracker/kodi.py
- trackma/ui/gtk/data/settingswindow.ui
- trackma/ui/qt/settings.py
- trackma/utils.py
Kodi tracking support, only works with the internal player (for now) and requires enabling `Settings -> Services -> Control -> Allow control of Kodi via HTTP` to work. 
Only tested with Kodi 18.8 but should work with any version that uses the [JSON-RPC API/v10](https://kodi.wiki/view/JSON-RPC_API/v10).
> Kodi tracker support

- trackma/tracker/inotifyBase.py
Sometimes, a process ends before we open ther /proc/<pid> directory and open() throws a FileNotFoundError.
If this excpetion is raised, we will silently ignore the pid and continue the loop.
> Handle inotifyBase FileNotFoundError.

- trackma/engine.py
- trackma/tracker/plex.py
Found an issue while using the plex tracker where upon closing the video the tracker would not update, and would continue to think the video was playing. I implemented a quick and dirty fix to allow for the update to occur. I also made hook calls print in debug mode as tracker_state spams the screen every tracker_interval
> [Plex Tracker] Update state on plex video close

- README.md
- trackma/engine.py
- trackma/tracker/jellyfin.py
- trackma/tracker/plex.py
- trackma/tracker/tracker.py
- trackma/ui/gtk/data/settingswindow.ui
- trackma/ui/gtk/settingswindow.py
- trackma/ui/qt/settings.py
- trackma/utils.py
Wanted trackma to keep track of my Jellyfin instance so I decided to fully implement it into the source code. I also added a view offset setting for the session info, I implemented this for one of my discord hooks to display where I am in the show. 
Some things to note for documentation:
- The API key in the config file is found in Jellyfin under Dashboard -> API Keys, where the user needs to generate this key and plug it into the config file. It seems that this can only be generated under an admin user
- The username in the config file is what user the user wants to track
> Added Jellyfin Tracker Support

- trackma/engine.py
This PR will close #540. If this is merged, trackma will follow the expected behavior instead of the current one.
> Update tracker after altname changes

- trackma/tracker/jellyfin.py
> [tracker/jellyfin] Remove protocol from url and use folder name for name of series

- hooks/presence.py
- ignore xesm-title
- use pydbus instead of dbus-python in MPRIS Tracker
- set ability to clear activity in pypresence hook.
> [HOOK] presence hook auto clear activity on idle.

- trackma/extras/redirections.py
***It's still 31st in my country, but HAPPY NEW YEAR FOLKS! :tada:***
---
Rules that end with `!` should automatically create a new rule where destination ID is redirected to itself.
```
- 10087|6028|10087:14-25 -> 11741|7658|11741:1-12!
```
The `!` in above rule creates another rule:
```
- 11741|7658|11741:14-25 -> 11741|7658|11741:1-12
```
> [Redirections] Handle self-redirecting rules

- trackma/ui/gtk/showtreeview.py
ProgressCellRenderer.do_get_size is a instance specific method
Using it as static makes gtk raise exceptions
> Gtk: Make ProgressCellRenderer.do_get_size() non-static

- tests/test_anime_info_extractor.py
- trackma/engine.py
- trackma/extras/AnimeInfoExtractor.py
By adding some test cases I collected on a certain website and from #413, I started rewriting a couple matchings in the show parsing algorithm without touching too much of the overarching logic, because that seemed to have worked quite well outside of the collected cases.
Tests are run using `pytest` in the repository root. I didn't add anything for documentation, however, since this is the only part that has tests now.
I tried to make the changes modular and have each commit stand on its own. Particularly notable changes are:
1. S01E01 parsing, where the season number is extracted into a separate attribute and then simply appended to the final show name because I didn't know what else to do it without refactoring. See https://github.com/z411/trackma/commit/c25077c19ff9644ff6cfb30c42dfb7b0 …
> Tweak show recognition code and add tests

- trackma/ui/qt/mainwindow.py
Fixes a bug where list syncing disables sorting.
> Qt: enable sorting after showlist update

- setup.py
- trackma/ui/gtk/__main__.py
- trackma/ui/qt/__init__.py
- trackma/ui/qt/__main__.py
- trackma/ui/qt/qt4.py
By introducing a `__main__` submodule in the gtk and qt packages, the
respective UIs can be launched through `python -m trackma.ui.gtk`, just
like has already been possible with cli and curses.
The gtk main function is moved to the __init__ module just like for the
others.
qt4 loader file has been renamed to remove duplication in the module
path ('trackma.ui.qt.qt4ui').
> Unify ui module launching code

- trackma/ui/qt/__init__.py
This feels really bad, but I have no experience with Qt or PyQt to think
of a better solution.
Fixes a regression of #493.
Qt4 is broken for me in general, even on stable, but I also don't have qt4 dependencies in my package manager anymore and would need to built them from the AUR. Since it's very old and we're on Qt6 already, maybe we should remove it?
> Fix Qt UI immediately closing itself

- trackma/ui/gtk/mainview.py
> [GTK] Improve "play episode" context menu

- trackma/ui/qt/accounts.py
When the extra field was added a few years back, it was only added to account creation, not updating. Since tokens expire for some sites, the following error would occur when someone went to update their token after their syncs started getting rejected:
> [Qt] fix account editing

- trackma/ui/qt/accounts.py
- trackma/ui/qt/mainwindow.py
Instead of showing an error that no account has been selected, prevent
clicking the buttons in the first place.
Also properly reset the "Edit" combo when any button is pressed and not
only "Update".
Just something I noticed while testing #618.
> Qt: Disable buttons in account switcher when they cannot be used

- hooks/episode_missing_ani-cli.py
- trackma/engine.py
- trackma/utils.py
Following suggestion on #610, I created a hook that is called whenever `Engine.play_episode()` fails to find a episode on the user library. I also created a hook example file using it, mimicking #610 behavior.
> Create episode_missing Hook

- trackma/lib/libmal.py
MAL's `start_date` wasn't being fetched before, so `utils.estimate_aired_episodes(show)` pratically always returned `total or 0`.
I also `import gzip`, because it's actually needed on a if branch (line 182).
> [libmal] fetch media (previously missing) start_date

- trackma/lib/libmal.py
trackma crashes when trying to display the results of a (manga) search query.
The `type_translate` dictionary only contained entries for anime, so I've added the missing ones for manga.
I got these entries from the API documentation example response, and I've also added light_novel, since that's apparently also a valid option.
The documentation also lists 'oel' as a type, not sure what that's about so I left that out.
fixes #627
> MAL API: update type_translate dict

- trackma/data.py
- trackma/engine.py
- trackma/lib/lib.py
- trackma/lib/libanilist.py
- trackma/lib/libkitsu.py
- trackma/lib/libmal.py
- trackma/lib/libshikimori.py
- trackma/lib/libvndb.py
- trackma/messenger.py
- trackma/tracker/inotify.py
- trackma/tracker/inotifyBase.py
- trackma/tracker/jellyfin.py
- trackma/tracker/kodi.py
- trackma/tracker/mpris.py
- trackma/tracker/plex.py
- trackma/tracker/polling.py
- trackma/tracker/pyinotify.py
- trackma/tracker/tracker.py
- trackma/tracker/win32.py
I changed the Messenger class to hold a internal class name. Every other class that uses the messenger (`Engine`, `Data`, `Lib` and `TrackerBase`), will instance the messenger class with their `self.name` only once, and every call to this instance, will optionally re-use the given name.
I say optionally, because `debug`, `info`, `warn` and `exception` can still receive a class name, so Hooks continue exactly the same: that's not a breaking change.
I searched and removed `self.name` from every `debug`, `info`, `warn` and `exception` call in the code base. As a bonus, almost every two-line call was inlined.
```
-     self.msg.warn(
-         self.name, "Unknown operation in queue (%s), skipping..." % repr(operation))
+     self.msg.warn("Unknown operation in queue (%s), skipping..." % …
```
> Simplify messenger calls

- README.md
OpenSUSE repo link removed as they no longer hosts trackma package
> [readme] Fixed links

- trackma/ui/qt/__init__.py
- trackma/ui/qt/mainwindow.py
I found this solution to Wayland not showing the icon for PyQt applications thanks to the KDE guidelines [here](https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon). 
I was having the same issue of the Wayland yellow and white icon showing in the application's title bar and in the task manager on the panel with some PyQt6 applications I made. When I added this line, it fixed the icon issue for both locations with my applications, but for some reason it's not fixing it for Trackma's title bar icon. Still, I figured this was better than nothing, as it fixes it for the task manager on the panel.
Edit:  I hadn't realized setDesktopFileName was already called in \_\_init\_\_.py. The second commit uses that original call instead of calling the function again. …
> Set desktop file name for Wayland icon

- trackma/lib/libkitsu.py
- trackma/utils.py
See title. Addresses the first part of #665 but does not do anything about the URLs only being cacheable for a limited amount of time. That will need separate logic.
Edit: I should mention this is untested.
> kitsu: Try multiple keys for image urls

- trackma/tracker/plex.py
- trackma/ui/gtk/data/settingswindow.ui
- trackma/ui/gtk/settingswindow.py
- trackma/ui/qt/settings.py
- trackma/utils.py
This would be a solution for Issue #369. 
The hardcoded http prevents any secure connections from being used. This pull request adds a configuration option to use ssl, which then prefixes https. This is not a perfect fix since it will still run into SSL certificate errors if only the server IP is used, but if the plex.direct url of the server is used, to which the certificate is issues it works without a problem.
Alternatively the SSL verification can be turned off, but that is not a good solution even if this solution puts the onus on the user to use the correct URL instead of simply the IP.
This fix also adds a checkbox toggle for the setting to the qt and gtk setting windows.
> Plex: Add SSL toggle

- trackma/lib/libshikimori.py
Shikimori changed its domain to `shikimori.me`:
- https://shikimori.me/forum/news/505429-novyy-domen-sayta-shikimori-me
- https://shikimori.me/forum/news/506738-novyy-domen-sayta-shikimori-me-v2
`shikimori.org` and `shikimori.one` still work, but they are left for compatibility.
Changes were tested by trying to log in via personal shikimori account.
> Change Shikimori endpoints from .org to .me

- trackma/ui/gtk/imagebox.py
- trackma/ui/qt/workers.py
Image.ANTIALIAS has been removed in PIL 10.0.0: https://pillow.readthedocs.io/en/stable/deprecations.html
Image.LANCZOS is identical but [it seems like overkill](https://github.com/z411/trackma/issues/698#issuecomment-1627437824).
> Replace Image.ANTIALIAS with Image.BICUBIC in QT and GTK

- hooks/episode_missing_ani-cli.py
~~Note: the hook is now blocking.~~
Also, i guess `utils.spawn_process` could be deprecated. The python team had quite the time to stabilize the subprocess module, maybe the zombie processes happening before doesn't happen anymore. The `os` module used is quite hard to understand.
> fix hook episode_missing_ani-cli.py episode loop

- trackma/ui/gtk/mainview.py
This continues the effort in #616, althrough, a simple one. 
I tested some designs in practice for some weeks, and ended with this, which is actually the same as the one i showed in https://github.com/z411/trackma/pull/616#discussion_r895049777.
It's simpler, because the "markings" now only convey a single piece of information: if the episode is available in the library or not; and, the information about being already watched or not, is still conveyed by the mere positioning of the numbers. This bring a more intuitive feel to the menu, as of before, a new user would probably take quite a while until they understand the meaning of the markings.
> GTK: change "Play episode" menu aesthetic

- trackma/lib/libmal.py
i found that MAL has type "cm" and type "tv_special" as media type and it crashed my trackma.
I'm not entirely sure if cm stands for commercial or for something else, so i defined it as utils.Type.other  
while tv_special gets redirected to specials so i put it as  utils.Type.special
examples
cm: Mirai no Watashi
tv_spcial: Wonder Egg Priority: Watashi no Priority
sry if something is missing it's my first pr
> add support for cm and tv_special media type on mal

- trackma/tracker/plex.py
Fixes #316. Tested on GTK, Qt, and CLI on Arch. 
Uses `urllib.parse.quote` to properly handle special characters in the username and password.
> Fix URL encoding for Plex login credentials

- trackma/lib/libmal.py
will prevent crash in cli/qt and infinit loading in gtk  if `item['media_type']` not in `self.type_translate`, now it  falls back to `utils.Type.UNKNOWN`.
eg.  `Mahoutsukai Reimeiki PV` with the media_type `pv` which is not a key in type_translate.
Could of cause be also fixed by adding `pv` to type_translate but then if something else is not in type_translate, it will crash and  a new fix would be needed.
> MAL: fallback to Unknown if media_type not in type_translate

- README.md
- trackma/lib/libkitsu.py
The [kitsu.io](https://kitsu.io) domain has expired, and the main developers do not have access to that domain. So they [migrated](https://github.com/hummingbird-me/kitsu-server/issues/1556#issuecomment-2282590908) to the new [kitsu.app](https://kitsu.app) domain.
This pull request updates all references of `kitsu.io` to `kitsu.app`.
> [Kitsu API] migrate from kitsu.io to kitsu.app

- trackma/engine.py
They are annoying and pretty useless. A full rescan will show better diagnostics for why a certain file wouldn't be recognized.
I've removed these locally many months ago and haven't missed them once.
> Remove debug prints of cache hits during scanning

- trackma/utils.py
Without this check, we would not be able to handle overlapping self-redirects, which is something that occurs in anime-relations.txt and that taiga handles by simply only redirecting if the recognized episode number is invalid. So we match this behavior.
See also https://github.com/erengy/anime-relations/issues/181.
> Redirect only invalid episodes

- trackma/engine.py
The multi-minute waiting time for a library rescan has been getting on my nerves for years now but today was finally the day I actually implemented caching. Since the standard number of episodes of a show is 12 episodes with some having more, this caching approximates to an at least 10x speedup in "usual" setups.
It's not the most ideal implementation but it works.
(Whenever I work on the trackma codebase, I feel how dated it is. The lack of type hinting and the questionable formatting definitely needs work, but that is for another time.)
> Add caching to library rescan

- trackma/engine.py
- trackma/ui/cli.py
Helps to rescan particular folders only, e.g. after adding an altname or when new files were added and the inotify tracker isn't used.
Improves the situation described in #677 but does not add a GUI option. I'm not sure if a GUI command for this functionality is even wanted by users (especially now that a rescan is much faster with #748).
> cli: add optional path parameter for the "rescan" command

- trackma/engine.py
- trackma/ui/cli.py
Clarifies that it does not undo the local changes (that's done by `retrieve`) and has symmetry with `viewqueue`.
Closes #681
> cli: Rename `undoall` to `clearqueue`

- trackma/engine.py
- trackma/ui/curses.py
- trackma/ui/gtk/window.py
- trackma/ui/qt/mainwindow.py
- trackma/utils.py
Continues the work of #727 but in a simpler fashion (as suggested in the review comments).
Since the code is identical for all UIs with the exception of determining the show id and error reporting, we move the common functionality to the engine and to a new small helper method in utils that defers to `spawn_process` (to re-use our already existing code to prevent zombie processes).
Because I had problems with the double-fork code for xdg-open here (unlike with mpv when playing episodes), I switched it to a different method that launches subprocesses normally via subprocess but also added a daemon thread to poll our created subprocesses and thus prevent them from remaining as zombies on \*NIX OSes.
Supersedes and closes #727
Fixes #525
Fixes #508
> Unify open folder

- hooks/presence.py
The change merged in b1c50643420fedde9e13f3063a755e494cf92d42 could not possibly have worked since it's referencing an attribute that was never created. 
I also changed the code to use a more ideomatic try-except block instead of `importlib.find_spec` and `__import__`.
Note that I did not actually test this.
> Fix setting "watching" activity

- README.md
- trackma/lib/libshikimori.py
- trackma/utils.py
Just noticed it uses old domain which can't be opened in browser (ERR_TOO_MANY_REDIRECTS). I believe adjusting domain to the current shikimori.one is fine and shouldn't cause any troubles.
> replace Shikimori domain to avoid redirection problems
