z411/trackma

trackma/lib/libplex.py
trackma/tracker.py
trackma/utils.py

Added experimental [plex media server](https://plex.tv/) support (need to manually set the configs for now, check the changes to utils.py) based off [one of my projects](https://github.com/Hairo/saya).

Experimental plex support (still no configurable)

---

trackma/tracker.py

Fixes 'Plex media server is not running' warning message spam.

Fix 'plex server is not running' message spam in the log

---

trackma/lib/libplex.py
trackma/tracker.py
trackma/ui/gtkui.py
trackma/ui/qtui.py

Plex config entries for GTK and Qt config dialogs, also some fixes to the plex lib so that it now supports the 'Player was closed before updating' feature.

Plex config entries for GTK and Qt GUIs

---

trackma/ui/qtui.py

Just as my previous + button in the gtk interface it has the same functionality.

Added a plus button to the qt interface.

---

trackma/lib/libplex.py

Should i add the licence statement at the start of the file?

General cleanup

---

trackma/ui/qtui.py

Line 219 was a duplicate of line 218.

Dupplicate code line.

---

trackma/engine.py

Hopefully these changes aren't horrendous or anything.
1. Changes `_search_video` to look for a file ***containing*** `episode` rather than only one ***ending*** with `episode`
1. Changes `play_episode` to return the last episode of the played file

Make play_episode work with multi-episode files

---

trackma/engine.py

This should fix the bug introduced by #109.

Fix check for if an episode is in the range of episodes in a file.

---

trackma/ui/gtkui.py

This commit adds a button similar to the + button but this button removes a eppisode.

Added a remove episode quick button to the GTK interface.

---

trackma/accounts.py
trackma/data.py
trackma/engine.py
trackma/lib/lib.py
trackma/lib/libanilist.py
trackma/lib/libhb.py
trackma/lib/libmal.py
trackma/lib/libmelative.py
trackma/lib/libvndb.py
trackma/messenger.py
trackma/tracker.py
trackma/ui/cli.py
trackma/ui/curses.py
trackma/ui/gtkui.py
trackma/ui/qtui.py
trackma/utils.py

To make sure no other changes happened, I recommend viewing the diff with `?w` option:
- https://github.com/z411/trackma/pull/125/files - normal diff
- https://github.com/z411/trackma/pull/125/files?w=1 - diff without whitespace changes

Removed trailing whitespace

---

trackma/ui/curses.py
trackma/utils.py

Add ability to change sort order in curses interface.

Curses edit

---

trackma/ui/curses.py
trackma/ui/gtkui.py
trackma/ui/qtui.py
trackma/utils.py

Small change to prevent potential lost configs re: comment on 7cad225

[Utils] Quit on config parse error

---

trackma/ui/gtkui.py

[Gtk] Bugfix: colours scoping issue on SearchView (#169)

---

trackma/ui/qtui.py

Made groupbox button on AccountManager more responsive for subsequent operations. Removed QVariant APIv1 artefacts (fixes #204)

[Qt] AccountManager fix

---

trackma/ui/curses.py

Updated the keymap defaults to match utils.
Added lists to the things to stringify for the show info (quick fix just to get it working again, the problem could be different for all I know).

[Curses] Fixed crash on startup, crash on show info.

---

setup.py
trackma/engine.py
trackma/extras/AnimeInfoExtractor.py
trackma/tracker.py
trackma/ui/qt4ui.py
trackma/ui/qtui.py
trackma/utils.py

Inotify trackers now add episodes to library when detected (via creation, moving into watched directory or even just general access), and remove episodes from library when deleted or moved out of the watch directory.
Improved multiepisode behaviour of library (no more gaps in Momokuri bar!).

[Library] Inotify and multiepisode support

---

README.md
trackma/lib/libanilist.py
trackma/lib/libhb.py
trackma/lib/libvndb.py

Updated other APIs to use HTTPS.
From what I've read into it, this should be all that's necessary to use https, check the certificates and somesuch, at least from Python 3.4 onward. But someone more knowledgeable is more than welcome to check the work.
Also the added security feature in the README is totally optional, that's why it's a seperate commit. 
I can always send a new pull without it.

Https everywhere

---

trackma/ui/qtui.py

Qt: Fix qt5 show percentage bug.

---

trackma/tracker.py

- Cut back on code duplication to make additions easier going forward
- Removed an edge case which used an undefined state (underlying issue with #255)
- The inotify and pyinotify trackers will no longer poll every second whenever a video is playing if not actively counting down for an update
- The update countdown will now only print every 5 seconds until the last 10 seconds to cut back on log spam

[Tracker] Refactor/clean up

---

trackma/ui/gtkui.py

Align elements properly and remove text size modification.

GTK preferences tweaks

---

trackma/ui/qtui.py

This fixes https://github.com/z411/trackma/issues/281

Fix a crash with qt5 UI when saving.

---

trackma/tracker/plex.py

As of the lastest plex update (1.4.4.3495) it no longer returns the full path of the videos in the usual url (http://host:port/status/sessions), apparently it only returns it for the non-transcoded files, this commit makes the tracker read filepath from somewhere else (http://host:port/library/metadata/id), thankfully this still works in the previous versions.

Fix the file paths in the lastest plex update

---

trackma/tracker/plex.py
trackma/ui/gtkui.py
trackma/ui/qtui.py
trackma/utils.py

Plex claimed servers support

---

trackma/ui/qtui.py

Only the GUI rows were sorted but the actual results weren't.

Qt: Fixed Add Dialog results sorting

---

trackma/ui/qtui.py

Working on adding feature parity across interfaces.
As a response to https://github.com/z411/trackma/issues/133.
Will work on cli interfaces next.

Qt: Added open containing folder

---

trackma/ui/cli.py

cli: Added open containing folder

---

trackma/ui/curses.py
trackma/utils.py

curses: Added open containing folder

---

trackma/ui/qtui.py
trackma/utils.py

Now the column by which the anime list is sorted is saved in config.

[QT] Remember sorting in anime list.

---

trackma/ui/gtkui.py

also fixes lists having empty strings in them
for example:
`['action','adventure','','','']` -> `action, adventure`

[GTK] Display lists nicely in detail window

---

trackma/ui/qtui.py

Use 1-1-1 date for unknown values

---

.pylintrc
trackma/engine.py
trackma/tracker/pyinotify.py
trackma/ui/curses.py
trackma/ui/gtkui.py
trackma/ui/qt/__init__.py
trackma/ui/qt/add.py
trackma/ui/qt/mainwindow.py
trackma/ui/qt/models.py
trackma/ui/qt/qt4ui.py

Trying to cleanup some code via Pylint. Most of the errors are gone, but there is still a huge list of warnings to work through. Also, I've made a few guesses about some changes here and there, and commented out code I didn't know what to do with.
Would pylint (or some other static analysis tooling) be something of interest to you? I don't think I'll have a lot of time to learn the code base and work through the majority of the problems.

[WIP] Pylint fixes

---

trackma/tracker/plex.py

Plex: Check for the user in both observe() and the xml info and Implement pause/playing functionality

---

trackma/ui/qt/mainwindow.py

[QT] Add library scan shortcut

---

trackma/ui/gtk/data/searchwindow.ui
trackma/ui/gtk/data/settingswindow.ui
trackma/ui/gtk/settingswindow.py
trackma/ui/gtk/statusicon.py
trackma/ui/gtk/window.py

Because I broke the tray with the refactor, now I'm fixing it again. The next one in the list is to restore keybindings.

Gtk: Fix tray interactions with main window

---

.gitignore
setup.py
trackma/ui/gtk/data/searchwindow.ui
trackma/ui/gtk/data/showinfobox.ui
trackma/ui/gtk/data/showinfowindow.ui
trackma/ui/gtk/searchwindow.py
trackma/ui/gtk/showinfobox.py

Enhanced Search Window and fixed search result not showing.
Added kwarg 'orientation' to set InfoBox orientation.

Some Enhancements and fixes for gtk ui.

---

hooks/tweet.py

Handle Twitter exception and show User the message returned by api.

Handle Twitter exception.

---

trackma/lib/libanilist.py
trackma/lib/libkitsu.py
trackma/lib/libshikimori.py

Fixes issues where trackma crashes if it cannot establish the HTTP connections with the API endpoints.

Handle urllib.error.URLError like urllib.request.HTTPError

---

trackma/ui/cli.py
trackma/ui/curses.py
trackma/ui/gtk/window.py
trackma/ui/qt/mainwindow.py

added openfolder support for macOS and Windows

---

trackma/ui/qt/__init__.py

Needed for [sway](https://github.com/swaywm/sway) window configuration. 
https://github.com/swaywm/sway/blob/master/sway/sway.5.scd#L795

Qt: Set name of application

---

trackma/utils.py

Missing edge case for redirection handling

If statement doesn't account for when the queued episode number equals the first tuple value in src_eps

---

trackma/engine.py
trackma/ui/gtk/main.py

Use double fork and waitpid to prevent zombie process in *nix

---

trackma/ui/gtk/mainview.py
trackma/ui/gtk/showtreeview.py

* Created ShowList class which is a child class of Gtk.TreeModelSort.
* Used ShowList to wrap Gtk.TreeModelFilter which wraps Gtk.ListStore.
* Implemented required methods in ShowList.
* Implemented #177.

Use sorted and  filtered global ListStore and implement #177 in Gtk UI.

---

trackma/ui/gtk/accountswindow.py
trackma/ui/gtk/settingswindow.py
trackma/ui/gtk/showtreeview.py
trackma/ui/gtk/window.py

* Add functions for properly showing tooltip
* Change Class structure for easier data retrieval

[Gtk UI] Tooltips

---

trackma/tracker/mpris.py

* Introduce repeated code as function
* Add `viewOffset` support

[MPRIS Tracker] Enhancements

---

trackma/engine.py
trackma/ui/qt/workers.py

Engine:
* support external function for creating detached process
Qt:
* Launch player using `QtCore.QProcess`

[Engine+Qt] Fixes

---

trackma/ui/gtk/mainview.py

In previous event handler, if total entries in `ShowList` wasn't
enough for the fired Scroll event to be handeled by `ShowList` then
it was passed to event handler of Notebook and it changed current
page, this behaviour was undesired.
The new event handler filters scroll event by using `Enter` and
`Leave` event fired by Notebook when pointer enters/leaves tab bar.

[GTK] fix scroll event in `Gtk.Notebook`

---

trackma/ui/gtk/showtreeview.py

* Fix `episode_str` with `string.format()` in `ShowList.update()`
* Reuse code from `ShowList.update()` in `ShowList.update_or_append()`

[GTK-UI] fix output format and optimize code.

---

trackma/lib/libmal.py

Some titles may return 'unknown' media_type

---

trackma/ui/gtk/mainview.py
trackma/ui/gtk/showtreeview.py
trackma/ui/gtk/window.py

﻿- Increase props max value in ProgressCellRenderer
- Make buttons insensetive while initializing engine

[UI/GTK] Fix warnings in ProgressCellRenderer

---

trackma/lib/libkitsu.py

* Use proper filter for manga.
* Handle anime/manga specific metadata.

[api/kitsu] Handle manga metadatas properly

---

trackma/engine.py

This PR introduces an optional `destroy` function in hook that will clean up the
hook when engine unloads.
﻿Closes #567

[Engine] Implement hook destroy method

---

trackma/ui/gtk/accountswindow.py
trackma/ui/gtk/showinfowindow.py

- [GTK] Force headerbar in AccountDialog, closes #553

[Gtk] AccountDialog headerbar fix.

---

trackma/tracker/mpris.py

As `dbus-python` is deprecated, I replaced it with pydbus in MPRIS tracker.

use pydbus instead of dbus-python in MPRIS Tracker

---

trackma/ui/gtk/showinfobox.py
trackma/ui/qt/add.py
trackma/ui/qt/models.py
trackma/ui/qt/widgets.py

[Qt] Fix Trackma crashing when opening "Search/Add from Remote" dialog

---

trackma/ui/cli.py

change `usage trackmer` to say `usage tracker`

Fix typo in cli.py

---

trackma/lib/libmal.py

This fix is mentioned as working in #626
And it will potentially close #584 
EDIT: Also take a look at my other PR :smile:

[libmal] Show unintenionally filtered anime in results again

---

trackma/engine.py
trackma/messenger.py
trackma/tracker/mpris.py
trackma/tracker/tracker.py

I added these while debugging why a certain episode wasn't being detected. Turns out that was because my anime relations were outdated (different issue).

Add more debug logging for episode redirection

---

trackma/ui/gtk/showtreeview.py

The tooltip would always act like the list is sorted as default (alphabetically). Now it always respects the current list.

[GTK] fix tooltip indexing on sorted list

---

trackma/tracker/win32.py

Add [mpv.net](https://github.com/stax76/mpv.net) detection by detecting by process name (`mpvnet.exe`).

[Win32 Tracker] Add mpv.net detection

---

hooks/presence.py

Closes #640
Resolves https://github.com/z411/trackma/issues/640#issuecomment-1263006607
It looks like this:
Disclaimer: I don't code in Python. So if I did something wrong, pointers are welcome.

[Discord RPC Hook] Add "View Anime", cover image and also track ignored episodes

---

docs/hooks.md

Now using markdown for better formatting and syntax highlighting
Added link to example file

[docs] Hooks docs improvements

---

trackma/ui/gtk/settingswindow.py

GTK: save tracker_update_wait_s value as int

---

trackma/ui/cli.py

Simple CLI completions fixes

---

trackma/engine.py

The non-deprecated way is to use the finder returned by `pkgutil.iter_modules` to "find" a module spec, then create a module from the spec and finally execute the module.
This fixes hooks in Python 3.13 and thus fixes #736.
Supersedes and closes #759.
Supersedes and closes #746.

Update hook import mechanism

---

trackma/ui/cli.py

Been bothering me for a while and after I read #776 again I figured it shouldn't be much effort to implement it.

Some improvements to the CLI "search" and "info" commands
